In [1]:
import cv2
from sklearn.cluster import KMeans
import matplotlib.pyplot as plt
import numpy as np
from collections import Counter
from skimage.color import rgb2lab, deltaE_cie76
import os

%matplotlib inline

In [2]:
cascade=cv2.CascadeClassifier('C:\\Users\\harsh\\frontalface_default.xml')
cascad=cv2.CascadeClassifier('C:\\Users\\harsh\\eye_detect.xml')
cascades=cv2.CascadeClassifier('C:\\Users\\harsh\\car_detect.xml')
img=cv2.imread('C:\\Users\\harsh\\OneDrive\\Pictures\\avengers.jpg')
gray_img=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
faces=cascade.detectMultiScale(gray_img,scaleFactor = 1.05,
                               minNeighbors=5)
print(type(faces))
print(faces)

eyes=cascad.detectMultiScale(gray_img,scaleFactor = 1.05,
                               minNeighbors=5)
print(type(eyes))
print(eyes)
count=0
for x,y,w,h in faces:
    img=cv2.rectangle(img,(x,y),(x+w,y+h),(255,0,0),5)
    count=count+1
print('number of faces:',count)
b=0
for x,y,w,h in eyes:
    img=cv2.rectangle(img,(x,y),(x+w,y+h),(3,255,0),5)
    b=b+1
print('number of eyes:',b)
resized=cv2.resize(img,(1200,700))
cv2.imshow('Gray',resized)
cv2.waitKey(0)

<class 'numpy.ndarray'>
[[2392 1419   31   31]
 [2024  870   62   62]
 [2709 1473   49   49]
 [1857  900   91   91]
 [1558 1388   68   68]
 [2247 1116  101  101]
 [2256  629  116  116]
 [1322 1230  110  110]
 [2074 1193  126  126]
 [2417 1348   86   86]
 [2227 1423   66   66]
 [2194 1726   72   72]
 [1267 1679   74   74]
 [2248 1375   29   29]
 [1247  159   42   42]
 [1691  582   48   48]
 [2163 1641  112  112]
 [1908 1486   67   67]
 [1243 1560   63   63]
 [2171 1941   36   36]
 [2599 1204   80   80]
 [1602  993   74   74]
 [1742  587  112  112]
 [1558  678   48   48]
 [2100  443  142  142]
 [1327  424  173  173]
 [2611 1256   84   84]
 [1438  668   56   56]
 [1148  694   82   82]
 [2244 1792   56   56]
 [1367  749   73   73]
 [2733  407   53   53]
 [1365  492  103  103]
 [1962  496   96   96]
 [2213 1313   61   61]]
<class 'numpy.ndarray'>
[[2235 1435   23   23]
 [1766 1253   27   27]
 [1584  584   52   52]
 [2428 1368   22   22]
 [2464 1370   24   24]
 [2259 1440   22   22]
 [1904  

-1